public with sharing class ClassDevelop1 
{
    public static void sendMessage()
    {
        System.debug('New Message');
        System.debug('New Message1');
        System.debug('New Message2');
        System.debug('New Message3');
        System.debug('New Message4');
        System.debug('New Message5');
        System.debug('New Message6');
        System.debug('New Message7');
        System.debug('New Message8');
        System.debug('New Message9');
        System.debug('New Message10');
        System.debug('New Message11');
        System.debug('New Message12');
        System.debug('New Message13');
        System.debug('New Message14');
        System.debug('New Message15');
    }
}
