/**
* @author Globant - ProjectName
* @description Description
* @date Date
* @group Group
* Version
* ---------------------------------------------------------------------------------------------------
* No.   Date        Author                  Description
* ---   -----       -------                 ---------------------------------------------------------
* 1.0   Date       AuthorName             Class creation
*/
public with sharing class ClassDevelop1 
{
    /**
    * @description MethodDescription 
    */
    public static void sendMessage()
    {
        System.debug(LoggingLevel.DEBUG,'New Message');
    }
}
