name: Validate PMD Rules

# Definition when the workflow should run
on:
    pull_request:
      types: [opened, synchronize]
      branches: [ develop ]
      paths:
        - 'force-app/**'          
jobs:
  pmd_job:
    runs-on: ubuntu-latest
    name: PMD job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run PMD
      uses: kemsakurai/action-pmd@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        tool_name: 'pmd_reviewdog'
        src_path: 'force-app/main/default/classes/'
        rulesets_path: 'PMDRules/PMDRules.xml'
        filter_mode: diff_context
    #Steps to identify how many violations and fail the job
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
        version: '6.40.0'
        sourcePath: 'force-app/main/default/classes/'
        rulesets: 'PMDRules/PMDRules.xml'
        analyzeModifiedFilesOnly: true
    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      uses: actions/github-script@v3
      with:
         script: |
                 core.setFailed('There are ' + ${{steps.pmd.outputs.violations}} + ' violations to PMD Rules, please fix them')
