# Unique name for this workflow
name: Validate PR on develop branch

# Definition when the workflow should run
on:
    # The workflow will run whenever an event happens on a pull request
    pull_request:
      # The events are that a PR is opened, or when a commit is pushed
      # to a branch that has an existing pull request
      types: [opened, synchronize]
      # The branches filter allows to specify that this workflow should only
      # run if the branch name is "develop". This way we prevent this workflow
      # from running when PRs are opened on other branches
      branches: [ develop ]
      # We only care about changes to the force-app directory, which is the
      # root directory of the sfdx project. This prevents the job from running
      # when changing non-salesforce files (like this yml file).
      paths:
        - 'force-app/**'
            

# Jobs to be executed when the above conditions are met
jobs:
    # This is the name of the job. You can give it whatever name you want
    validate-deployment-on-develop-org:
        runs-on: ubuntu-latest
        env: 
          USERNAME: jeissonhernandez@playful-shark-eyl510.com
          URLORG: https://login.salesforce.com
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: '11'
          - uses: pmd/pmd-github-action@v1
            id: pmd
            with:
              version: '6.40.0'
              sourcePath: 'force-app/main/default/classes/'
              rulesets: 'PMDRules/PMDRules.xml'
              analyzeModifiedFilesOnly: true
              
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v1
            with:
                 sarif_file: pmd-report.sarif
                 
          - name: Fail build if there are violations
            run: |
                if [[ ${{ steps.pmd.outputs.violations }} != 0 ]]; then echo "Game over!" exit 0; else exit 1; fi
